### ISSUE TITLE
Feed Caching Update Code in Ad Schedules Does Not Work

### ISSUE THREAD

**Issue by cyface** [podiobooks/podiobooks#336]
We aren't using the feed caching at the moment, so this is not urgent, but the "on save" hook in the admin for Ad Schedules does not work with the title many-to-many  - it tries to update the related titles before the Ad Schedule has been updated, and causes anything you do with the Ad Schedule to barf.

So, at some point we should update the commented out code in podiobooks/ads/admin.py with something that works with many-to-many models, but it's not urgent.

**Comment by Brant** [comment]
I've done this before. From what I found, there was no easy way to do it. You just had to save the object, grab the key, then re-query to grab the many-to-many models and update accordingly.

e.g.:

```python
class SliderImageSetAdmin(admin.ModelAdmin):
    inlines = [SliderImageInSetInlineAdmin, ]
    list_display = ["name", "date_active", "active", ]
    readonly_fields = ['slug', ]

    def clone_image_set(self, request, queryset):
        if len(queryset) > 1:
            self.message_user(request, "You may only clone one at a time", level=messages.ERROR)
        else:
            item = queryset[0]
            slides = item.slides.all()

            new_item = item
            new_item.id = None
            new_item.name = "%s (CLONE)" % new_item.name
            new_item.date_active = None
            new_item.save()

            for slide in slides:
                new_slide = models.SliderImageInSet(slider_image=slide, slider_image_set=new_item)
                new_slide.save()

    clone_image_set.short_description = "Clone Image Set"

    actions = [clone_image_set, ]
```

That particularly example uses a "through" relation... but it's the basic idea.
