### ISSUE TITLE
Mass Update Duration Data Across All Episodes

### ISSUE THREAD

**Issue by cyface** [podiobooks/podiobooks#340]
We hard-coded episode durations on the initial PB1 import, need to write a batch job to go through old titles and grab fresh duration data from libsyn.

**Comment by tlwhit2** [comment]
Code is in, just need to run the batch job in prod. Should probably tweak it to more cleanly ignore certain episode naming issues.

**Comment by cyface** [comment]
Done.  Fixed with SHA: 80bb18536fb2907d364bbe7b488f28b98d335cd8 .

However there are a few problem child episodes that will need to be manually fixed, and or the script made more robust.  Titles with one or more problem episodes include:

hackoffcom
the-sorcerers-secret
the-secret-world-chronicle-book-three-world-well-lost
the-secret-world-chronicle-book-five-waiting-on
the-inner-chapters-volume-1
the-gearheart-maiden-flight-of-the-avenger
the-birth-of-propaganda
spherical-tomi-a-novel-of-despair
singularity
serve-it-cold
serpentine-street
personal-effects-sword-of-blood
max-quick-1-the-pocket-and-the-pendant
marwan
morevi-the-chronicles-of-rafe-and-askana-remastered
lost-gods
loner-in-space
live-from-milwaukee-its-tuesday-night (not on libsyn)
ida
hunting-the-five
dreaming-of-deliverance
dorotheas-song
borrowed-time
axiom-man
anne-of-green-gables (not on libsyn)
against-the-tide-mp3-edition
7th-son-book-two-deceit-the-beta-version
